[workspace]
members = [
    "test_app"
]

[package]
name = "renderforge"
version = "0.2.2"
edition = "2024"
description = "A Rendering framework built on top of glow"
license = "GPL-3.0-only"
repository = "https://github.com/westbot657/RenderForge"
readme = "README.md"
keywords = ["rendering", "opengl"]
categories = ["rendering"]
exclude = ["/test_app"]

[features]
default = ["opengl"]
opengl = ["wgpu/gles"]
vulkan = ["wgpu/vulkan"]

[dependencies]
wgpu = { version = "27.0.1", features = ["std", "glsl", "vulkan", "spirv", "angle", "gles", "wgsl", "vulkan-portability"] }
glam = { version = "0.32.0" }
shaderc = "0.10.1"
pollster = "0.4.0"
thiserror = { version = "2.0.16" }


