
[package]
name = "test_app"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
renderforge = { path = "../../RenderForge", features = ["egui"] }
egui = { version = "0.33.3", features = ["mint"] }
egui-winit = { version = "0.33.3", features = ["bytemuck", "wayland", "clipboard"] }
egui-wgpu = "0.33.3"
glam = "0.32.0"
bytemuck = "1.25.0"
wgpu = "27.0.1"
winit = "0.30.12"
pollster = "0.4.0"
